package src.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.sql.SQLException;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

import src.controller.CategoryController;
import src.model.Category;

public class CategoryDialog extends JDialog {

    private CategoryController categoryController;
    private Category newCategory; // To store the newly created category

    private JTextField nameField;
    private JTextField descriptionField;
    private JComboBox<String> typeComboBox;
    private JButton saveButton;
    private JButton cancelButton;

    public CategoryDialog(Frame owner, CategoryController categoryController) {
        super(owner, "Add New Category", true); // Modal
        this.categoryController = categoryController;
        this.newCategory = null;

        setLayout(new BorderLayout(10, 10));
        ((JPanel) getContentPane()).setBorder(new EmptyBorder(10, 10, 10, 10));
        getContentPane().setBackground(Color.WHITE);
        // setSize(350, 250); // Adjust as needed
        setLocationRelativeTo(owner);
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        initComponents();
        pack(); // Adjust size to components
    }

    private void initComponents() {
        JPanel formPanel = new JPanel(new GridBagLayout());
        formPanel.setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;

        // Name
        gbc.gridx = 0;
        gbc.gridy = 0;
        formPanel.add(new JLabel("Name:"), gbc);
        gbc.gridx = 1;
        nameField = new JTextField(20);
        formPanel.add(nameField, gbc);

        // Description
        gbc.gridx = 0;
        gbc.gridy = 1;
        formPanel.add(new JLabel("Description:"), gbc);
        gbc.gridx = 1;
        descriptionField = new JTextField(20);
        formPanel.add(descriptionField, gbc);

        // Type
        gbc.gridx = 0;
        gbc.gridy = 2;
        formPanel.add(new JLabel("Type:"), gbc);
        gbc.gridx = 1;
        typeComboBox = new JComboBox<>(new String[]{"Expense", "Income"});
        formPanel.add(typeComboBox, gbc);

        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.setBackground(Color.WHITE);
        saveButton = new JButton("Save");
        styleButton(saveButton);
        cancelButton = new JButton("Cancel");
        styleButton(cancelButton);
        buttonPanel.add(saveButton);
        buttonPanel.add(cancelButton);

        add(formPanel, BorderLayout.CENTER);
        add(buttonPanel, BorderLayout.SOUTH);

        // Action Listeners
        saveButton.addActionListener(e -> saveCategory());
        cancelButton.addActionListener(e -> dispose());
    }

    private void styleButton(JButton button) {
        button.setBackground(new Color(220, 220, 220));
        button.setForeground(Color.BLACK);
        button.setFocusPainted(false);
    }

    private void saveCategory() {
        String name = nameField.getText().trim();
        String description = descriptionField.getText().trim();
        String type = (String) typeComboBox.getSelectedItem();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category name cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            nameField.requestFocus();
            return;
        }

        // The Category constructor you provided: Category(String name, String description, String type)
        // And Category(int id, String name, String description, String type)
        // For a new category, ID is auto-generated by DB.
        Category category = new Category(name, description, type); // Uses the constructor without ID

        try {
            categoryController.addCategory(category);
            // If addCategory in controller sets the ID on the passed category object
            // (e.g., if DAO's insert method returns generated key and controller updates it)
            // then 'category' object here would have its ID.
            // For simplicity, we assume TransactionDialog will re-fetch categories to get the new one with ID.
            this.newCategory = category; // Store it, though ID might not be set unless controller/DAO handles it
            JOptionPane.showMessageDialog(this, "Category added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (SQLException e) {
            this.newCategory = null;
            JOptionPane.showMessageDialog(this, "Error adding category: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Call this method after the dialog is closed to get the category that was added.
     * Returns null if the dialog was canceled or if there was an error.
     * Note: The ID of the returned category might not be set if not handled by controller/DAO post-insert.
     * The caller (TransactionDialog) will typically refresh its category list from the controller anyway.
     */
    public Category getNewCategory() {
        return newCategory;
    }
}